import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import App from "./App";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <App>
      <html lang="en">
        <body className={`min-h-screen bg-bg_all`} >
          <div className="w-full h-full backdrop-blur-lg bg-gradient-to-r from-gray-950/80 to-gray-950/50">
            <Header />
            <div className="flex">
              <Sidebar />
              <div className="w-full h-[calc(100vh-80px)] overflow-y-auto">
                {children}
              </div>
            </div>
          </div>
        </body>
      </html>
    </App>
  );
}
